---
name: "Setup groff (GNU roff)"
author: Yevhen Fabizhevskyi
description: "This action sets up groff (GNU roff)."
branding:
  icon: terminal
  color: gray-dark
inputs:
  force:
    description: |
      If "false" skips installation if groff is already installed. If "true"
      installs groff in any case. Defaults to "false".
    required: false
    default: "false"
outputs:
  installed:
    description: Whether groff was installed or not.
    value: "${{ steps.install-groff.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'Windows' }}
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh

    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Install groff
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-groff
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          apt-get update
          apt-get install groff -y
        else
          brew install groff
        fi
      shell: sh

    - name: Print version
      run: groff --version
      shell: sh
